name: Format Check

on:
    pull_request:

permissions:
    contents: read
    pull-requests: read

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                persist-credentials: true

            - name: Format C++ code
              uses: OlleKReutercrona/clang-format@main
              with:
                  exclude: 'External/.'
                        